### ISSUE TITLE
Weird behavior with the scheduler

### ISSUE THREAD

**Issue by jedisct1** [dpc/mioco#80] opened 2016-01-22 08:35 UTC
I'm trying to get multiple consumers for a single producer

```rust
extern crate mioco;

use std::sync::Arc;
use mioco::mail;
use mioco::sync::Mutex;

fn main() {
    mioco::start_threads(5, move || {
        let (boxout, boxin) = mail::mailbox::<u64>();
        mioco::spawn(move || {
            let mut x = 0u64;
            loop {
                boxout.send(x);
                x = x + 1;
                mioco::sleep(500);
            }
        });

        let xboxin = Arc::new(Mutex::new(boxin));
        let xboxin2 = xboxin.clone();
        mioco::spawn(move || {
            loop {
                let x = { xboxin.lock().unwrap().read() };
                println!("{}\tA", x);
                mioco::sleep(2500);
            }
        });

        mioco::spawn(move || {
            loop {
                let x = { xboxin2.lock().unwrap().read() };
                println!("{}\tB", x);
                mioco::sleep(500);
            }
        });
        Ok(())
    });
}
```

This is what happens:

```
0	A
1	B
2	B
3	B
4	B
5	A
6	A
7	A
8	A
9	A
10	A
11	A
12	A
13	A
14	A
15	A
16	A
17	A
18	A
19	A
20	A
...
```
And it goes on and on, only `A` is printed from now on.

Everything quickly gets consumer by the first consumer coroutine, and only it. Nothing gets consumed by the second one any more.
`A` is the slow coroutine, which is sleeping for 2500ms, while `B` is yielding faster (500ms), so shouldn't the opposite happen?

**Comment by dpc** [comment] 2016-01-22 18:33
I think this is a bug. I think mailbox was supposed to be  mpsc, and Receiving end not Clone-able, but I need to double check that.

I understand that for this scenario you'd like mpmc queue. Another thing to address in #76 .

Thanks for reporting this!

**Comment by dpc** [comment] 2016-02-20 04:29
Oh, I've noticed that you're using `mioco::sync::Mutex`.

**Comment by dpc** [comment] 2016-02-25 23:32
I'm unable to reproduce. Maybe it was .. hmm... timing issue. Depends on how many cores you have or something. I'm going to close it, but if you have some followup, feel free to re-open.

**Closed by dpc** 2016-02-25 23:32 UTC
