### ISSUE TITLE
build failure with nightly

### ISSUE THREAD

**Issue by gregwebs** [dpc/mioco#118] opened 2016-03-20 13:19 UTC
I am a new rust user. It seems mioco can only be compiled on nightly due to its usage of features. On nightly I get the following error:

```
/root/.cargo/registry/src/github.com-88ac128001ac3a9a/mioco-0.4.0/src/coroutine.rs:246:35: 246:47 error: no method named `into_inner` found for type `std::panic::AssertRecoverSafe<F>` in the current scope
/root/.cargo/registry/src/github.com-88ac128001ac3a9a/mioco-0.4.0/src/coroutine.rs:246                 coroutine_user_fn.into_inner()()
                                                                                                                         ^~~~~~~~~~~~
/root/.cargo/registry/src/github.com-88ac128001ac3a9a/mioco-0.4.0/src/coroutine.rs:246:35: 246:47 help: items from traits can only be used if the trait is implemented and in scope; the following traits define an item `into_inner`, perhaps you need to implement one of them:
/root/.cargo/registry/src/github.com-88ac128001ac3a9a/mioco-0.4.0/src/coroutine.rs:246:35: 246:47 help: candidate #1: `std::sys_common::IntoInner`
/root/.cargo/registry/src/github.com-88ac128001ac3a9a/mioco-0.4.0/src/coroutine.rs:246:35: 246:47 help: candidate #2: `net2::IntoInner`
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `mioco`.
```

**Comment by dpc** [comment] 2016-03-20 22:15
Fixed in 0.4.1. Thanks for reporting!

**Closed by dpc** 2016-03-20 22:15 UTC

**Comment by gregwebs** [comment] 2016-03-20 22:30
Thanks for fixing! I did run into another issue

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading mioco v0.4.1
   Compiling mioco v0.4.1
/root/.cargo/registry/src/github.com-88ac128001ac3a9a/mioco-0.4.1/src/coroutine.rs:238:37: 238:61 error: cannot invoke tuple struct constructor with private fields [E0450]
/root/.cargo/registry/src/github.com-88ac128001ac3a9a/mioco-0.4.1/src/coroutine.rs:238             let coroutine_user_fn = panic::AssertRecoverSafe(coroutine_user_fn);
                                                                                                                           ^~~~~~~~~~~~~~~~~~~~~~~~
/root/.cargo/registry/src/github.com-88ac128001ac3a9a/mioco-0.4.1/src/coroutine.rs:238:37: 238:61 help: run `rustc --explain E0450` to see a detailed explanation
error: aborting due to previous error
Could not compile `mioco`.
```

**Comment by dpc** [comment] 2016-03-23 03:51
I can't reproduce. I think you might have to update to the latest nightly.

**Comment by gregwebs** [comment] 2016-03-23 08:37
Yeah, I was using a docker image that hasn't been updated for 2 weeks. I updated to the latest nightly and it worked.
